name: Runners_Scale
inputs:
  RUNNER_TAG:
    type: TEXT
    name: Runner tag
    info: Leave empty for untagged runners
  RUNNER_SLOTS:
    type: TEXT
    name: Number of slots per runner
    default: "2"
    info: Leave empty to calculate value from license
  MAX_RUNNERS:
    type: TEXT
    name: Maximum number of runners
  MIN_FREE_SLOTS:
    type: TEXT
    name: Minimum number of free slots
    default: "1"
docker_image_name: buddy/runners-scale
docker_image_tag: latest
working_directory: /buddy
execute_commands:
  - . calc.sh
output:
  variables:
    RUNNERS:
      example: "2"
      info: Number of runners
    RUNNER_SLOTS:
      example: "4"
    RUNNER_TAG:
      example: "TAG"
